name: cv4rs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - nodefaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - pillow
  - pytorch=2.5
  - torchvision=0.20
  - torchaudio=2.5
  - cuda=12.1
  - python-lmdb
  - wandb
  - safetensors
  - timm
  - pyarrow
  - pip=24.3.1=pyh8b19718_0
  - pip:
      - sympy==1.13.1
      - zennit==0.5.1

